users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('<int:pk>/like_videos/', views.LikeListView.as_view(), name='like_videos'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('reset_password_done/', views.reset_password_done, name='reset_password_done'),
]

videos/urls.py
from django.urls import path

from . import views

app_name = 'videos'
urlpatterns = [
    path('index', views.IndexView.as_view(), name='index'),
    path('search/', views.SearchListView.as_view(), name='search'),
    path('detail/<int:pk>/', views.VideoDetailView.as_view(), name='detail'),
    path('like/', views.like, name='like'),
]

youtube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from videos import views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('myadmin/', include('myadmin.urls')),
                  path('users/', include('users.urls')),
                  path('videos/', include('videos.urls')),
                  path('comments/', include('comments.urls')),
                  path('', views.IndexView.as_view(), name='home'),  # 默认首页
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/base.html
{% load static %}
<html>
<head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
    <meta name="keywords" content="最新电影,高清完整版,经典电影,国语配音,国英双语,中英字幕,蓝光电影,蓝光转压,影视分享,电影首发" />
    <meta name="description" content="Ace-Film最新电影,资源分享,高清完整版,经典电影,国语配音,国英双语,中英字幕,电影线上看"/>
    <meta name="google-site-verification" content="UhrjUG70pwiY6Sp4u4p5Q3ol8iD7yx4ZSwmGBpoaWik"/>
    <link href="{% static 'img/favicon.ico' %}" rel="icon" type="image/x-icon">
    <title>电影线上看</title>

    <link href="https://cdn.staticfile.org/semantic-ui/2.4.1/semantic.min.css" rel="stylesheet" type="text/css">
    <link href="{% static 'css/semantic.custom.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    {% block css %}{% endblock css %}

    <script>
    var _hmt = _hmt || [];
    (function() {
      var hm = document.createElement("script");
      hm.src = "https://hm.baidu.com/hm.js?e3be3decd24d944e0bc592558617d210";
      var s = document.getElementsByTagName("script")[0];
      s.parentNode.insertBefore(hm, s);
    })();

    </script>

</head>
<body>

{% include "base/header.html" %}
<div class="ui container" id="v-content">
    {% block content %}
    {% endblock content %}
</div>

<script src="https://cdn.staticfile.org/jquery/1.9.0/jquery.min.js"></script>
<script src="https://cdn.staticfile.org/semantic-ui/2.4.1/semantic.min.js"></script>
<script>
    var search_url = "{% url 'videos:search' %}"

</script>
<script src="{% static 'js/header.js' %}"></script>

{% block javascript %}
{% endblock javascript %}

{% block modal %}
{% endblock modal %}

</body>
</html>

templates/base/footer.html
{% load static %}

<div class="ui vertical footer segment ">
    <div class="ui center aligned container">
        <div class="ui divider"></div>
        <img src="{% static 'img/logo.png' %}" class="ui centered mini image">
        <div class="ui horizontal   small divided link list">
            <p class="item" >电影线上看</p>
            <p class="item" >本网站所有电影信息来自互联网，本站不存储任何电影资源，如有侵权，请立即联系我删除</p>
            <a class="item" target="_blank" href="http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=SCkrLWUuISQlCC4nMCUpISRmKycl" style="text-decoration:none;">给我写信</a>
        </div>
    </div>
</div>

templates/base/form_errors.html
{% if form.errors %}
<div class="ui info message">
    <ul class="list">

        {% for field in form %}
        {% for error in field.errors %}
        <li class="item">{{ error|escape }}</li>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <li class="item">{{ error|escape }}</li>
        {% endfor %}
    </ul>
</div>

{% endif %}

templates/base/form_messages.html
{% if messages %}
<div class="ui info message">
    {% for message in messages %}
    <div class="item">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

templates/base/header.html
{% load static %}
{% load thumbnail %}

<div class="ui sticky fixed  menu">
    <div class="ui container">
        <a class="borderless header item" href="/"><img class="logo" src="{% static 'img/logo.png' %}">AceFilm</a>
        <div class="v-header-extra">
            <div class="ui small icon input v-video-search">
                <input class="prompt" id="v-search" placeholder="搜索视频" type="text" value="{{ q }}">
                <i class="search icon" id="search" style="cursor:pointer;"></i>
            </div>

            {% if user.is_authenticated %}
            <div class="ui inline dropdown" id="v-header-avatar" style="">
                <div class="" style="display:inline-block;font-weight:bold;">
                    {% thumbnail user.avatar "200x200" crop="center" as im %}
                    <img class="ui avatar image" src="{{ im.url }}">
                    {% empty %}
                    <img class="ui avatar image" src="{% static 'img/img_default_avatar.png' %}">
                    {% endthumbnail %}
                    {{ user.username }}
                </div>
                <i class="dropdown icon"></i>
                <div class="menu">
                    <div class="item" onclick="window.location='{% url 'users:profile' user.pk %}';">
                        <i class="user icon"></i>
                        <span>个人资料</span>
                    </div>
                    <div class="item" onclick="window.location='{% url 'users:like_videos' user.pk %}';">
                        <i class="heart icon"></i>
                        <span>我的喜欢</span>
                    </div>
                    <div class="item" onclick="window.location='{% url 'users:logout' %}';">
                        <i class="sign-out icon"></i>
                        <span>退出</span>
                    </div>
                </div>
            </div>
            {% else %}
            <a class="ui tiny secondary basic button" href="{% url 'users:login' %}?next={{ request.path }}"
               id="v-header-login">登录</a>
            <a class="ui tiny secondary basic button" href="{% url 'users:signup' %}?next={{ request.path }}"
               id="v-header-signup">注册</a>
            {% endif %}

        </div>
    </div>
</div>

templates/base/left_nav.html
<div class="ui secondary vertical pointing menu">
    <a class="link item" href="{% url 'users:profile' user.pk %}" id="id_profile">
        <i class="grey user icon"></i>
        <span class="v-nav-title">个人资料</span>
    </a>
    <a class="link item" href="{% url 'users:change_password' %}" id="id_password">
        <i class="grey edit icon"></i>
        <span class="v-nav-title">修改密码</span>
    </a>
</div>

templates/base/page_nav.html
{% if is_paginated %}
<div class="video-page">
    <div class="ui circular labels">
        {% if page_obj.has_previous %}
        <a class="ui circular label"
           href="?page={{ page_obj.previous_page_number }}{% if c %}&c={{c}}{% endif %}{% if q %}&q={{q}}{% endif %}">&lt;</a>
        {% endif %}
        {% for i in page_list %}
        {% if page_obj.number == i %}
        <a class="ui red circular label">{{ i }}</a>
        {% else %}
        <a class="ui circular label" href="?page={{ i }}{% if c %}&c={{c}}{% endif %}{% if q %}&q={{q}}{% endif %}">{{ i }}</a>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <a class="ui circular label"
           href="?page={{ page_obj.next_page_number }}{% if c %}&c={{c}}{% endif %}{% if q %}&q={{q}}{% endif %}">&gt;</a>
        {% endif %}
    </div>
</div>
{% endif %}