comments/urls.py
from django.urls import path

from . import views

app_name = 'comments'
urlpatterns = [
    path('submit_comment/<int:pk>', views.submit_comment, name='submit_comment'),
    path('get_comments/', views.get_comments, name='get_comments'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('<int:pk>/like_videos/', views.LikeListView.as_view(), name='like_videos'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('reset_password_done/', views.reset_password_done, name='reset_password_done'),
]

videos/urls.py
from django.urls import path

from . import views

app_name = 'videos'
urlpatterns = [
    path('index', views.IndexView.as_view(), name='index'),
    path('search/', views.SearchListView.as_view(), name='search'),
    path('detail/<int:pk>/', views.VideoDetailView.as_view(), name='detail'),
    path('like/', views.like, name='like'),
]

youtube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from videos import views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('myadmin/', include('myadmin.urls')),
                  path('users/', include('users.urls')),
                  path('videos/', include('videos.urls')),
                  path('comments/', include('comments.urls')),
                  path('', views.IndexView.as_view(), name='home'),  # 默认首页
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

videos/models.py
import datetime
import os

from django.conf import settings
from django.db import models
from django.dispatch import receiver


class VideoQuerySet(models.query.QuerySet):
    def get_count(self):
        return self.count()

    def get_today_count(self):
        return self.exclude(create_time__lt=datetime.date.today()).count()

    def get_published_count(self):
        return self.filter(status=0).count()

    def get_not_published_count(self):
        return self.filter(status=1).count()

    def get_published_list(self):
        return self.filter(status=0).order_by('-create_time')

    def get_search_list(self, q):
        if q:
            return self.filter(title__contains=q).order_by('-create_time')
        else:
            return self.order_by('-create_time')

    def get_recommend_list(self):
        return self.filter(status=0).order_by('-view_count')[:3]  # 推荐前3条观看最多的视频


class Classification(models.Model):
    """
    分类表
    字段有title(分类名称)和status(是否启用)
    """

    list_display = ('title',)
    title = models.CharField(max_length=100, blank=True, null=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'CLASSIFICATIONS'


class Video(models.Model):
    """
    classification是一个ForeignKey外键字段，表示一个分类对应多个视频，一个视频对应一个分类(多对一)
    """

    STATUS_CHOICES = (
        ('0', '发布中'),
        ('1', '未发布'),
    )
    title = models.CharField(max_length=30, blank=True, null=True)
    classification = models.ForeignKey(Classification, on_delete=models.CASCADE, null=True)
    cover = models.ImageField(upload_to='cover/', blank=True, null=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, blank=True, null=True)
    view_count = models.IntegerField(default=0, blank=True)
    liked = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='liked_videos')  # 喜欢的用户
    create_time = models.DateTimeField(auto_now_add=True, blank=True, max_length=20)
    link = models.CharField(max_length=300, blank=True, null=True)

    objects = VideoQuerySet.as_manager()

    class Meta:
        db_table = 'VIDEOS'

    def increase_view_count(self):
        self.view_count += 1
        self.save(update_fields=['view_count'])

    def switch_like(self, user):
        if user in self.liked.all():
            self.liked.remove(user)
        else:
            self.liked.add(user)

    def count_likers(self):
        return self.liked.count()

    def user_liked(self, user):
        if user in self.liked.all():
            return 0
        else:
            return 1


@receiver(models.signals.post_delete, sender=Video)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    删除FileField文件
    """

    if instance.cover:
        if os.path.isfile(instance.cover.path):
            os.remove(instance.cover.path)

videos/forms.py
from django import forms

from comments.models import Comment


class CommentForm(forms.ModelForm):
    content = forms.CharField(error_messages={'required': '评论不能为空', },
                              widget=forms.Textarea(attrs={'placeholder': '请输入评论内容（200个字以内）'}))

    class Meta:
        model = Comment
        fields = ['content']

videos/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views import generic
from django.views.decorators.http import require_http_methods

from helpers import get_page_list, ajax_required
from .forms import CommentForm
from .models import Video, Classification


class IndexView(generic.ListView):
    model = Video
    template_name = 'videos/index.html'
    context_object_name = 'video_list'
    paginate_by = 12
    c = None

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        page_list = get_page_list(paginator, page)
        classification_list = Classification.objects.filter(status=True).values()
        context['c'] = self.c
        context['classification_list'] = classification_list
        context['page_list'] = page_list
        return context

    def get_queryset(self):
        self.c = self.request.GET.get('c', None)
        if self.c:
            classification = get_object_or_404(Classification, pk=self.c)
            return classification.video_set.all().order_by('-create_time')
        else:
            return Video.objects.filter(status=0).order_by('-create_time')


class SearchListView(generic.ListView):
    model = Video
    template_name = 'videos/search.html'
    context_object_name = 'video_list'
    paginate_by = 8
    q = ''

    def get_queryset(self):
        self.q = self.request.GET.get('q', '')
        return Video.objects.filter(title__contains=self.q).filter(status=0)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(SearchListView, self).get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        page_list = get_page_list(paginator, page)
        context['page_list'] = page_list
        context['q'] = self.q
        return context


class VideoDetailView(generic.DetailView):
    model = Video
    template_name = 'videos/detail.html'

    def get_object(self, queryset=None):
        obj = super().get_object()
        obj.increase_view_count()
        return obj

    def get_context_data(self, **kwargs):
        context = super(VideoDetailView, self).get_context_data(**kwargs)
        recommend_list = Video.objects.get_recommend_list()
        form = CommentForm()
        context['form'] = form
        context['recommend_list'] = recommend_list
        return context


@ajax_required
@require_http_methods(['POST'])
def like(request):
    if not request.user.is_authenticated:
        return JsonResponse({'code': 1, 'msg': '请先登录'})
    video_id = request.POST['video_id']
    video = Video.objects.get(pk=video_id)
    user = request.user
    video.switch_like(user)
    return JsonResponse({'code': 0, 'likes': video.count_likers(), 'user_liked': video.user_liked(user)})

templates/videos/ad.html
{% load static %}

<a target="_blank" href="http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=SCkrLWUuISQlCC4nMCUpISRmKycl">
    <img src="{% static 'img/ad.jpg' %}" height="200" width="333">
</a>

templates/videos/detail.html
{% extends 'base/base.html' %}
{% load static %}
{% load video_tag %}
{% block css %}
<link href="{% static 'css/dropload.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
<div class="ui unstackable two column grid">
    <div class=" ten wide column">
        <div>
            <iframe class="vip" src="{{ video.link }}" scrolling="no" border="0" allowfullscreen="true" frameborder="0"></iframe>
            <p>请勿相信视频里的任何广告!!!不能播放请<a class="item" target="_blank" href="http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=SCkrLWUuISQlCC4nMCUpISRmKycl" style="text-decoration:none;">给我写信</a>(主题写电影名字)</p>
        </div>
        <div class="video-info">
            <div>
                <span class="video-title">{{ video.title }}</span>
                <!--span class="video-view-count">{{ video.view_count }}次播放</span-->
                <span class="float-right">
                    <i class="like {%  user_liked_class video user %} icon cursor" id="like" video-id="{{ video.id }}"></i>
                    <span id="like-count">{{ video.count_likers }}</span>
                </span>
            </div>
            <div class="ui divider"></div>
        </div>

        <div class="ui comments">
            {% if user.is_authenticated %}
            <form class="ui reply form" id="comment_form" method="post" action="{% url 'comments:submit_comment' video.pk %}">
                {% csrf_token %}
                <div class="field">
                    {{form.content}}
                    <input type="hidden" value="{{ video.id }}" name="video_id">
                </div>
                <button class="ui primary button" type="submit">
                    添加评论
                </button>
                <div class="ui info message n">
                    <div class="item" id="comment-result"></div>
                </div>
            </form>
            {% else %}
            <div>
                <p><a href="{% url 'users:login' %}?next={{ request.path }}">登录</a>后即可评论</p>
            </div>
            {% endif %}
            <div class="comment-list"></div>
        </div>
    </div>
    <div class="six wide column">
        {% include "videos/recommend.html" %}
        {% include "videos/ad.html" %}

    </div>
</div>
{% endblock content %}

{% block javascript %}

<script>
var comments_url = "{% url 'comments:get_comments' %}"
var video_id = {{ video.id }}
</script>

<script src="{% static 'js/dropload.js' %}"></script>
<script src="{% static 'js/load_comments.js' %}"></script>
<script src="{% static 'js/detail.js' %}"></script>
{% endblock javascript %}
 

templates/videos/index.html
{% extends 'base/base.html' %}
{% load static %}
{% load thumbnail %}
{% load video_tag %}

{% block content %}

<div class="classification">
    <a class="ui {% if c %}{% else %}red{% endif %} label" href="{% url 'home' %}">全部</a>
    {% for item in classification_list %}
    <a class="ui {% if c == item.id|stringformat:'s' %}red{% endif %} label" href="?c={{ item.id }}">{{ item.title }}</a>
    {% endfor %}
</div>

<div class="ui hidden divider"></div>
<div class="ui grid">
    {% for item in video_list %}
    <div class="four wide column">
        <div class="ui card">
            <a class="image" href="{% url 'videos:detail' item.pk %}">
                {% thumbnail item.cover "300x400" crop="center" as im %}
                <img class="ui image" src="{{ im.url }}">
                {% empty %}
                {% endthumbnail %}
            </a>
            <div class="content">
                <a class="header" target="_blank" href="{% url 'videos:detail' item.pk %}">{{ item.title }}</a>
                <div class="meta">
                    <span class="date">{{ item.create_time|time_since}}</span>
                    <!--span class="float-right">{{ item.view_count}}次播放</span-->
                </div>
            </div>
        </div>
    </div>
    {% empty %}
    <h3>暂无数据</h3>
    {% endfor %}
</div>

{% include "base/page_nav.html" %}

{% include "base/footer.html" %}

{% endblock content %}

templates/videos/recommend.html
{% load thumbnail %}

<span class="video-side-title">推荐列表</span>
<div class="ui unstackable divided items">

    {% for item in recommend_list %}
    <div class="item">
        <div class="ui tiny image">
            <a class="image" href="{% url 'videos:detail' item.pk %}">
                {% thumbnail item.cover "300x200" crop="center" as im %}
                <img class="ui image" src="{{ im.url }}">
                {% empty %}
                {% endthumbnail %}
                <i class="large play icon v-play-icon"></i>
            </a>
        </div>
        <div class="middle aligned content">
            <a class=" header-title" href="{% url 'videos:detail' item.pk %}">{{ item.title }}</a>
            <div class="meta">
                <!--span class="description">{{ item.view_count }}次播放</span-->
            </div>
        </div>
    </div>
    {% empty %}
    <h3>暂无推荐</h3>
    {% endfor %}

</div>

templates/videos/search.html
{% extends 'base/base.html' %}
{% load static %}
{% load thumbnail %}
{% load video_tag %}

{% block content %}

<h3 class="ui header">搜索结果</h3>
<div class="ui unstackable items">

    {% for item in video_list %}
    <div class="item">
        <a class="image" href="{% url 'videos:detail' item.pk %}">
                {% thumbnail item.cover "300x400" crop="center" as im %}
                <img class="ui image" src="{{ im.url }}">
                {% empty %}
                {% endthumbnail %}
                <i class="large play icon v-play-icon"></i>
        </a>
        <div class="content">
            <a class="header" href="{% url 'videos:detail' item.pk %}">{{ item.title }}</a>
            <div class="meta">
                <span class="date">发布于{{ item.create_time|time_since}}</span>
            </div>
            <!-- div class="description">
                {{ item.view_count}}次观看
            </div -->
        </div>
    </div>
    {% empty %}
    <h3>暂无数据</h3>
    {% endfor %}

</div>

{% include "base/page_nav.html" %}


{% endblock content %}

{% block javascript %}
<script  type="text/javascript" >
$('.ui .dropdown').dropdown();
</script>
{% endblock javascript %}