myadmin/urls.py
from django.urls import path

from . import views

app_name = 'myadmin'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    # 总览
    path('', views.IndexView.as_view(), name='index'),

    # 视频管理
    path('video_list/', views.VideoListView.as_view(), name='video_list'),
    path('video_today/', views.VideoListViewToday.as_view(), name='video_today'),
    path('video_add/', views.AddVideoView.as_view(), name='video_add'),

    path('chunked_upload/', views.MyChunkedUploadView.as_view(), name='api_chunked_upload'),
    path('chunked_upload_complete/', views.MyChunkedUploadCompleteView.as_view(), name='api_chunked_upload_complete'),

    path('video_publish/<int:pk>/', views.VideoPublishView.as_view(), name='video_publish'),
    path('video_publish_success/', views.VideoPublishSuccessView.as_view(), name='video_publish_success'),
    path('video_edit/<int:pk>/', views.VideoEditView.as_view(), name='video_edit'),
    path('video_delete/', views.video_delete, name='video_delete'),

    path('video_nopublish/', views.VideoListViewNoPublish.as_view(), name='video_nopublish'),
    path('video_publishing/', views.VideoListViewPublishing.as_view(), name='video_publishing'),

    # 分类管理
    path('classification_add/', views.ClassificationAddView.as_view(), name='classification_add'),
    path('classification_list/', views.ClassificationListView.as_view(), name='classification_list'),
    path('classification_edit/<int:pk>/', views.ClassificationEditView.as_view(), name='classification_edit'),
    path('classification_delete/', views.classification_delete, name='classification_delete'),

    # 用户管理
    path('user_add/', views.UserAddView.as_view(), name='user_add'),
    path('user_list/', views.UserListView.as_view(), name='user_list'),
    path('user_today/', views.UserListViewToday.as_view(), name='user_today'),
    path('user_edit/<int:pk>', views.UserEditView.as_view(), name='user_edit'),
    path('user_delete/', views.user_delete, name='user_delete'),

    # 评论管理
    path('comment_list/', views.CommentListView.as_view(), name='comment_list'),
    path('comment_today/', views.CommentListViewToday.as_view(), name='comment_today'),
    path('comment_delete/', views.comment_delete, name='comment_delete'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('<int:pk>/like_videos/', views.LikeListView.as_view(), name='like_videos'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('reset_password_done/', views.reset_password_done, name='reset_password_done'),
]

youtube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from videos import views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('myadmin/', include('myadmin.urls')),
                  path('users/', include('users.urls')),
                  path('videos/', include('videos.urls')),
                  path('comments/', include('comments.urls')),
                  path('', views.IndexView.as_view(), name='home'),  # 默认首页
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myadmin/models.py
from chunked_upload.models import ChunkedUpload


# Create your models here.
class MyChunkedUpload(ChunkedUpload):
    pass


# Override the default ChunkedUpload to make the `user` field nullable
MyChunkedUpload._meta.get_field('user').null = True

myadmin/views.py
import datetime
import logging

from chunked_upload.views import ChunkedUploadView, ChunkedUploadCompleteView
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.http import JsonResponse
from django.shortcuts import *
from django.views import generic
from django.views.decorators.http import require_http_methods
from django.views.generic import TemplateView

from comments.models import Comment
from helpers import get_page_list, AdminUserRequiredMixin, ajax_required, SuperUserRequiredMixin
from users.models import User
from videos.models import Video, Classification
from .forms import UserLoginForm, VideoPublishForm, VideoEditForm, UserAddForm, UserEditForm, ClassificationAddForm, \
    ClassificationEditForm
from .models import MyChunkedUpload

logger = logging.getLogger('my_logger')


def login(request):
    if 'POST' == request.method:
        form = UserLoginForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if user is not None and user.is_staff:
                auth_login(request, user)
                return redirect('myadmin:index')
            else:
                form.add_error('', '请输入管理员账号')
    else:
        form = UserLoginForm()
    return render(request, 'myadmin/login.html', {'form': form})


def logout(request):
    auth_logout(request)
    return redirect('myadmin:login')


class IndexView(AdminUserRequiredMixin, generic.View):
    """
    总览数据
    """

    def get(self, request):
        video_count = Video.objects.get_count()
        video_today_count = Video.objects.get_today_count()
        video_has_published_count = Video.objects.get_published_count()
        video_not_published_count = Video.objects.get_not_published_count()
        user_count = User.objects.count()
        user_today_count = User.objects.exclude(date_joined__lt=datetime.date.today()).count()
        comment_count = Comment.objects.get_count()
        comment_today_count = Comment.objects.get_today_count()
        data = {
            'video_count': video_count,
            'video_today_count': video_today_count,
            'video_has_published_count': video_has_published_count,
            'video_not_published_count': video_not_published_count,
            'user_count': user_count,
            'user_today_count': user_today_count,
            'comment_count': comment_count,
            'comment_today_count': comment_today_count
        }
        return render(self.request, 'myadmin/index.html', data)


class AddVideoView(SuperUserRequiredMixin, TemplateView):
    template_name = 'myadmin/video_add.html'


class MyChunkedUploadView(ChunkedUploadView):
    model = MyChunkedUpload
    field_name = 'the_file'


class MyChunkedUploadCompleteView(ChunkedUploadCompleteView):
    model = MyChunkedUpload

    def on_completion(self, uploaded_file, request):
        print('uploaded--->', uploaded_file.name)
        pass

    def get_response_data(self, chunked_upload, request):
        video = Video.objects.create(cover=chunked_upload.file)
        return {'code': 0, 'video_id': video.id, 'msg': 'success'}


class VideoPublishView(SuperUserRequiredMixin, generic.UpdateView):
    model = Video
    form_class = VideoPublishForm
    template_name = 'myadmin/video_publish.html'

    def get_context_data(self, **kwargs):
        context = super(VideoPublishView, self).get_context_data(**kwargs)
        clf_list = Classification.objects.all().values()
        clf_data = {'clf_list': clf_list}
        context.update(clf_data)
        return context

    def get_success_url(self):
        return reverse('myadmin:video_publish_success')


class VideoPublishSuccessView(generic.TemplateView):
    template_name = 'myadmin/video_publish_success.html'


class VideoEditView(SuperUserRequiredMixin, generic.UpdateView):
    model = Video
    form_class = VideoEditForm
    template_name = 'myadmin/video_edit.html'

    def get_context_data(self, **kwargs):
        context = super(VideoEditView, self).get_context_data(**kwargs)
        clf_list = Classification.objects.all().values()
        clf_data = {'clf_list': clf_list}
        context.update(clf_data)
        return context

    def get_success_url(self):
        messages.success(self.request, "保存成功")
        return reverse('myadmin:video_edit', kwargs={'pk': self.kwargs['pk']})


@ajax_required
@require_http_methods(['POST'])
def video_delete(request):
    if not request.user.is_superuser:
        return JsonResponse({'code': 1, 'msg': "无删除权限"})
    video_id = request.POST['video_id']
    instance = Video.objects.get(id=video_id)
    instance.delete()
    return JsonResponse({'code': 0, 'msg': 'success'})


class VideoListView(AdminUserRequiredMixin, generic.ListView):
    model = Video
    template_name = 'myadmin/video_list.html'
    context_object_name = 'video_list'
    paginate_by = 10
    q = ''

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(VideoListView, self).get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        page_list = get_page_list(paginator, page)
        context['page_list'] = page_list
        context['q'] = self.q
        return context

    def get_queryset(self):
        self.q = self.request.GET.get('q', '')
        return Video.objects.get_search_list(self.q)


class VideoListViewToday(VideoListView):
    def get_queryset(self):
        now = datetime.datetime.now()
        start_time = now - datetime.timedelta(hours=23, minutes=59, seconds=59)
        return Video.objects.filter(create_time__gt=start_time).order_by('-create_time')


class VideoListViewNoPublish(VideoListView):
    def get_queryset(self):
        return Video.objects.filter(status='1').order_by('-create_time')


class VideoListViewPublishing(VideoListView):
    def get_queryset(self):
        return Video.objects.filter(status='0').order_by('-create_time')


class ClassificationListView(AdminUserRequiredMixin, generic.ListView):
    model = Classification
    template_name = 'myadmin/classification_list.html'
    context_object_name = 'classification_list'
    paginate_by = 10
    q = ''

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ClassificationListView, self).get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        page_list = get_page_list(paginator, page)
        context['page_list'] = page_list
        context['q'] = self.q
        return context

    def get_queryset(self):
        self.q = self.request.GET.get('q', '')
        return Classification.objects.filter(title__contains=self.q)


class ClassificationAddView(SuperUserRequiredMixin, generic.View):
    def get(self, request):
        form = ClassificationAddForm()
        return render(self.request, 'myadmin/classification_add.html', {'form': form})

    def post(self, request):
        form = ClassificationAddForm(data=request.POST)
        if form.is_valid():
            form.save(commit=True)
            return render(self.request, 'myadmin/classification_add_success.html')
        return render(self.request, 'myadmin/classification_add.html', {'form': form})


@ajax_required
@require_http_methods(['POST'])
def classification_delete(request):
    if not request.user.is_superuser:
        return JsonResponse({'code': 1, 'msg': '无删除权限'})
    classification_id = request.POST['classification_id']
    instance = Classification.objects.get(id=classification_id)
    instance.delete()
    return JsonResponse({'code': 0, 'msg': 'success'})


class ClassificationEditView(SuperUserRequiredMixin, generic.UpdateView):
    model = Classification
    form_class = ClassificationEditForm
    template_name = 'myadmin/classification_edit.html'

    def get_success_url(self):
        messages.success(self.request, '保存成功')
        return reverse('myadmin:classification_edit', kwargs={'pk': self.kwargs['pk']})


class UserListView(AdminUserRequiredMixin, generic.ListView):
    model = User
    template_name = 'myadmin/user_list.html'
    context_object_name = 'user_list'
    paginate_by = 10
    q = ''

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        page_list = get_page_list(paginator, page)
        context['page_list'] = page_list
        context['q'] = self.q
        return context

    def get_queryset(self):
        self.q = self.request.GET.get('q', '')
        return User.objects.filter(username__contains=self.q).order_by('-date_joined')


class UserListViewToday(UserListView):
    def get_queryset(self):
        now = datetime.datetime.now()
        start_time = now - datetime.timedelta(hours=23, minutes=59, seconds=59)
        return User.objects.filter(date_joined__gt=start_time).order_by('-date_joined')


class UserAddView(SuperUserRequiredMixin, generic.View):
    def get(self, request):
        form = UserAddForm()
        return render(self.request, 'myadmin/user_add.html', {'form': form})

    def post(self, request):
        form = UserAddForm(data=request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data.get('password')
            user.set_password(password)
            user.save()
            return render(self.request, 'myadmin/user_add_success.html')
        return render(self.request, 'myadmin/user_add.html', {'form': form})


class UserEditView(SuperUserRequiredMixin, generic.UpdateView):
    model = User
    form_class = UserEditForm
    template_name = 'myadmin/user_edit.html'

templates/myadmin/classification_add.html
{% extends 'myadmin/base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}

<div class="ui grid">
    <div class="row">
        <h3>分类添加</h3>
    </div>
    <div class="ui divider"></div>
    <div class="row">
        <div class="v-form-wrap">

            <form class="ui form" novalidate method="post" action="{% url 'myadmin:classification_add' %}"
                  enctype="multipart/form-data" role="form">
                {% csrf_token %}
                <div class="field">
                    <label>分类名称</label>
                    {{ form.title }}
                </div>
                <div class="field">
                    <div class="ui checkbox">
                      {{form.status}}
                      <label>是否启用</label>
                    </div>
                </div>

                <button class="ui primary button" type="submit">添加</button>

                {% include "base/form_errors.html" %}
                {% include "base/form_messages.html" %}

            </form>


        </div>
    </div>
</div>


{% endblock content %}

templates/myadmin/classification_add_success.html
{% extends 'myadmin/base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}

<div class="ui grid">
    <div class="row">
        <h3>分类添加</h3>
    </div>
    <div class="ui divider"></div>
    <div class="row">
        <div class="v-form-wrap">

            <h3>添加成功！</h3>
            <h3><a href="{% url 'myadmin:classification_list' %}">&lt;&lt;返回列表</a></h3>
        </div>
    </div>
</div>


{% endblock content %}

templates/myadmin/classification_list.html
{% extends 'myadmin/base.html' %}
{% load static %}

{% block content %}

<div class="ui grid">
    <div class="row">
        <h3 class="ui header six wide column">分类列表</h3>
        <div class="v-title-extra ten wide column">
            <div class="ui action input v-admin-search">
                <input type="text" placeholder="Search..."  value="{{q}}" id="v-search">
                <button class="ui small button" id="search">搜索</button>
            </div>
        </div>
    </div>
    <div class="ui divider"></div>
    <div class="row">
        <table class="ui unstackable single line striped selectable table">
            <thead>
            <tr><th>名称</th></th><th>状态</th><th>操作</th></tr>
            </thead>
            <tbody class="video-list">

            {% for item in classification_list %}
            <tr classification-id="{{item.id}}">
                <td> {{item.title}}</td>
                <td> {% if item.status %}启用{% else %}未启用{% endif %}</td>
                <td>
                    <a class="ui primary button classification-edit" href="{% url 'myadmin:classification_edit' item.id %}">编辑</a>
                    <a class="ui button classification-delete">删除</a>
                </td>
            </tr>
            {% empty %}
            <h3>暂无数据</h3>
            {% endfor %}

            </tbody>
            <tfoot>
            <tr>
                <th colspan="6">
                    {% include 'myadmin/page_nav.html' %}
                </th>
            </tr>
            </tfoot>
        </table>
    </div>
</div>


{% endblock content %}

{% block modal %}
{% include "myadmin/classification_delete.html" %}
{% endblock modal %}

{% block javascript %}
<script>
    var search_url = "{% url 'myadmin:classification_list' %}"
    var api_classification_delete = "{% url 'myadmin:classification_delete' %}"
</script>
<script src="{% static 'js/myadmin/classification_list.js' %}"></script>
{% endblock javascript %}

templates/myadmin/classification_list_modal.html
<!--- 删除模态框 -->
<div class="ui tiny modal delete">
    <div class="header">
        删除确认
    </div>
    <div class="image content">
        <div class="description">
            确认删除分类(该分类下面的视频将会被删除)？
        </div>
    </div>
    <div class="actions">
        <div class="ui primary approve button">确认</div>
        <div class="ui deny button">取消</div>
    </div>
</div>

templates/myadmin/comment_delete.html
<!--- 删除模态框 -->
<div class="ui tiny modal delete">
    <div class="header">删除评论</div>
    <div class="image content">
        <div class="description">确认删除该条评论？</div>
    </div>
    <div class="actions">
        <div class="ui primary approve button">确认</div>
        <div class="ui deny button">取消</div>
    </div>
</div>

templates/myadmin/index.html
{% extends 'myadmin/base.html' %}
{% load static %}

{% block content %}

<div class="ui grid">
    <div class="row">
        <h3>总览</h3>
    </div>
    <div class="ui divider"></div>
    <div class="row">

        <div>

            <div class="ui hidden divider"></div>
            <div class="ui hidden divider"></div>

            <div class="ui tiny statistics">
                <div class="statistic">
                    <div class="value">{{ video_count }}</div>
                    <div class="label">总电影数</div>
                </div>
                <div class="statistic">
                    <div class="value">{{ video_today_count }}</div>
                    {% if video_today_count > 0 %}
                        <div class="label"><a href="{% url 'myadmin:video_today' %}">今日新增</a></div>
                    {% else %}
                        <div class="label">今日新增</div>
                    {% endif %}
                </div>
                <div class="statistic">
                    <div class="value">{{ video_has_published_count }}</div>
                    {% if video_has_published_count > 0 %}
                        <div class="label"><a href="{% url 'myadmin:video_publishing' %}">发布中</a></div>
                    {% else %}
                        <div class="label">发布中</div>
                    {% endif %}
                </div>
                <div class="statistic">
                    <div class="value">{{ video_not_published_count }}</div>
                    {% if video_not_published_count > 0 %}
                        <div class="label"><a href="{% url 'myadmin:video_nopublish' %}">未发布</a></div>
                    {% else %}
                        <div class="label">未发布</div>
                    {% endif %}
                </div>
            </div>

            <div class="ui hidden divider"></div>
            <div class="ui hidden divider"></div>
            <div class="ui hidden divider"></div>

            <div class="ui tiny statistics">
                <div class="statistic">
                    <div class="value">{{ user_count }}</div>
                    <div class="label">总用户数</div>
                </div>
                <div class="statistic">
                    <div class="value">{{ user_today_count }}</div>
                    {% if user_today_count > 0 %}
                        <div class="label"><a href="{% url 'myadmin:user_today' %}">今日新增</a></div>
                    {% else %}
                        <div class="label">今日新增</div>
                    {% endif %}
                </div>
            </div>

            <div class="ui hidden divider"></div>
            <div class="ui hidden divider"></div>
            <div class="ui hidden divider"></div>

            <div class="ui tiny statistics">
                <div class="statistic">
                    <div class="value">{{ comment_count }}</div>
                    <div class="label">总评论数</div>
                </div>
                <div class="statistic">
                    <div class="value">{{ comment_today_count }}</div>
                    {% if comment_today_count > 0 %}
                        <div class="label"><a href="{% url 'myadmin:comment_today' %}">今日新增</a></div>
                    {% else %}
                        <div class="label">今日新增</div>
                    {% endif %}
                </div>
            </div>

            <div class="ui hidden divider"></div>
            <div class="ui hidden divider"></div>
            <div class="ui hidden divider"></div>
            <div class="ui hidden divider"></div>
            <div class="ui hidden divider"></div>
            <div class="ui hidden divider"></div>

        </div>

    </div>
</div>

{% endblock content %}

templates/myadmin/user_add.html
{% extends 'myadmin/base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}

<div class="ui grid">
    <div class="row">
        <h3>用户添加</h3>
    </div>
    <div class="ui divider"></div>
    <div class="row">
        <div class="v-form-wrap">

            <form class="ui form" novalidate method="post" action="{% url 'myadmin:user_add' %}"
                  enctype="multipart/form-data" role="form">
                {% csrf_token %}
                <div class="field">
                    <label>用户名</label>
                    {{ form.username }}
                </div>
                <div class="field">
                    <label>密码</label>
                    {{ form.password }}
                </div>
                <div class="field">
                    <div class="ui checkbox">
                      {{form.is_staff}}
                      <label>管理员账号</label>
                    </div>
                </div>

                <button class="ui primary button" type="submit">添加</button>

                {% include "base/form_errors.html" %}
                {% include "base/form_messages.html" %}

            </form>


        </div>
    </div>
</div>


{% endblock content %}

templates/myadmin/user_delete.html
<!--- 删除模态框 -->
<div class="ui tiny modal delete">
    <div class="header">
        删除用户
    </div>
    <div class="image content">
        <div class="description">
            确认删除该用户？
        </div>
    </div>
    <div class="actions">
        <div class="ui primary approve button">确认</div>
        <div class="ui deny button">取消</div>
    </div>
</div>

templates/myadmin/user_edit.html
{% extends 'myadmin/base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}

<div class="ui grid">
    <div class="row">
        <h3>用户编辑</h3>
    </div>
    <div class="ui divider"></div>
    <div class="row">
        <div class="v-form-wrap">

            <form class="ui form" novalidate method="post" action="{% url 'myadmin:user_edit' form.instance.pk %}"
                  enctype="multipart/form-data" role="form">
                {% csrf_token %}
                <div class="field">
                    <label>用户名</label>
                    {{ form.username }}
                </div>
                <div class="field">
                    <div class="ui checkbox">
                      {{form.is_staff}}
                      <label>管理员账号</label>
                    </div>
                </div>

                <button class="ui primary button" type="submit">保存</button>

                {% include "base/form_errors.html" %}
                {% include "base/form_messages.html" %}

            </form>


        </div>
    </div>
</div>


{% endblock content %}

{% block modal %}
{% endblock modal %}

templates/myadmin/video_add.html
{% extends 'myadmin/base.html' %}
{% load static %}

{% block content %}

<div class="ui grid">
    <div class="row">
        <h3>添加电影</h3>
    </div>
    <div class="ui divider"></div>
    <div class="row">
        <div class="v-form-wrap">
            {% csrf_token %}
            <label id="progress_label" class="ui large blue label" for="chunked_upload">
                <i class="upload icon"></i> 上传封面
                <input id="chunked_upload" type="file" name="the_file" hidden>
            </label>
            <div id="progress_layout" class="n">
                <div class="ui progress" data-percent="74" id="upload_progress">
                    <div class="bar">
                        <div class="progress"></div>
                    </div>
                    <div class="label" id="upload_label">正在上传...</div>
                </div>
            </div>

            <div id="next_layout" class="n">
                <button id="next" class="ui primary right labeled icon button">
                  <i class="right arrow icon"></i>
                  下一步
                </button>

            </div>

        </div>
    </div>
</div>


{% endblock content %}

{% block modal %}
{% endblock modal %}

{% block javascript %}

<script>
var api_chunked_uplad = "{% url 'myadmin:api_chunked_upload' %}";
var api_chunked_upload_complete = "{% url 'myadmin:api_chunked_upload_complete' %}";
</script>

<script src="{% static 'js/upload/jquery.js' %}"></script>
<script src="{% static 'js/upload/jquery.ui.widget.js' %}"></script>
<script src="{% static 'js/upload/jquery.iframe-transport.js' %}"></script>
<script src="{% static 'js/upload/jquery.fileupload.js' %}"></script>
<script src="{% static 'js/upload/spark-md5.js' %}"></script>
<script src="https://cdn.staticfile.org/semantic-ui/2.4.1/semantic.min.js"></script>
<script src="{% static 'js/myadmin/video_upload.js' %}"></script>

{% endblock javascript %}

templates/myadmin/video_delete.html
<!--- 删除模态框 -->
<div class="ui tiny modal delete">
    <div class="header">
        删除电影
    </div>
    <div class="image content">
        <div class="description">
            确认删除该电影？
        </div>
    </div>
    <div class="actions">
        <div class="ui primary approve button" href="{{ request.path }}">确认</div>
        <div class="ui deny button">取消</div>
    </div>
</div>

templates/myadmin/video_list_modal.html
<!--- 删除模态框 -->
<div class="ui tiny modal delete">
    <div class="header">
        删除视频
    </div>
    <div class="image content">
        <div class="description">
            确认删除该条视频？
        </div>
    </div>
    <div class="actions">
        <div class="ui primary approve button" href="{{ request.path }}">确认</div>
        <div class="ui deny button">取消</div>
    </div>
</div>

templates/myadmin/video_publish.html
{% extends 'myadmin/base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}

<div class="ui grid">
    <div class="row">
        <h3>视频资料</h3>
    </div>
    <div class="ui divider"></div>
    <div class="row">
        <div class="v-form-wrap">

            <form class="ui form" novalidate method="post" action="{% url 'myadmin:video_publish' form.instance.pk %}"
                  enctype="multipart/form-data" role="form">
                {% csrf_token %}
                <input name="video_id" id="video_id" type="hidden">
                <div class="field">
                    <label>视频标题</label>
                    {{ form.title }}
                </div>
                <div class="field">
                    <label>第三方播放链接</label>
                    {{ form.link }}
                </div>
                <div class="field">
                    <label>视频分类</label>
                    <div class="ui selection  dropdown">
                        {{ form.classification  }}
                        <i class="dropdown icon"></i>
                        <div class="default text">请选择</div>
                        <div class="menu">
                            {% for item in clf_list %}
                            <div class="item" data-value="{{item.id}}">{{item.title}}</div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                 {{form.status}}
                <div class="field">
                    <label>视频封面</label>
                    {% if video.cover %}
                    {% thumbnail video.cover "300x400" crop="center" as im %}
                      <img class="ui small image" src="{{ im.url }}">
                    {% empty %}
                    {% endthumbnail %}
                    {% endif %}
                </div>

                <button class="ui primary button" type="submit">发布</button>

                {% include "base/form_errors.html" %}
                {% include "base/form_messages.html" %}

            </form>


        </div>
    </div>
</div>


{% endblock content %}

{% block modal %}
{% endblock modal %}

{% block javascript %}

<script>
$(function(){

    $('.ui .dropdown').dropdown();

});
</script>

{% endblock javascript %}

templates/myadmin/video_publish_success.html
{% extends 'myadmin/base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}

<div class="ui grid">
    <div class="row">
        <h3>电影资料</h3>
    </div>
    <div class="ui divider"></div>
    <div class="row">
        <div class="v-form-wrap">

            <h3>发布成功！</h3>
            <h3><a href="{% url 'myadmin:video_add' %}">继续添加</a></h3>

        </div>
    </div>
</div>


{% endblock content %}