users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('<int:pk>/like_videos/', views.LikeListView.as_view(), name='like_videos'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('reset_password_done/', views.reset_password_done, name='reset_password_done'),
]

videos/urls.py
from django.urls import path

from . import views

app_name = 'videos'
urlpatterns = [
    path('index', views.IndexView.as_view(), name='index'),
    path('search/', views.SearchListView.as_view(), name='search'),
    path('detail/<int:pk>/', views.VideoDetailView.as_view(), name='detail'),
    path('like/', views.like, name='like'),
]

youtube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from videos import views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('myadmin/', include('myadmin.urls')),
                  path('users/', include('users.urls')),
                  path('videos/', include('videos.urls')),
                  path('comments/', include('comments.urls')),
                  path('', views.IndexView.as_view(), name='home'),  # 默认首页
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    avatar = models.FileField(upload_to='avatar/')

    class Meta:
        db_table = 'USERS'

videos/models.py
import datetime
import os

from django.conf import settings
from django.db import models
from django.dispatch import receiver


class VideoQuerySet(models.query.QuerySet):
    def get_count(self):
        return self.count()

    def get_today_count(self):
        return self.exclude(create_time__lt=datetime.date.today()).count()

    def get_published_count(self):
        return self.filter(status=0).count()

    def get_not_published_count(self):
        return self.filter(status=1).count()

    def get_published_list(self):
        return self.filter(status=0).order_by('-create_time')

    def get_search_list(self, q):
        if q:
            return self.filter(title__contains=q).order_by('-create_time')
        else:
            return self.order_by('-create_time')

    def get_recommend_list(self):
        return self.filter(status=0).order_by('-view_count')[:3]  # 推荐前3条观看最多的视频


class Classification(models.Model):
    """
    分类表
    字段有title(分类名称)和status(是否启用)
    """

    list_display = ('title',)
    title = models.CharField(max_length=100, blank=True, null=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'CLASSIFICATIONS'


class Video(models.Model):
    """
    classification是一个ForeignKey外键字段，表示一个分类对应多个视频，一个视频对应一个分类(多对一)
    """

    STATUS_CHOICES = (
        ('0', '发布中'),
        ('1', '未发布'),
    )
    title = models.CharField(max_length=30, blank=True, null=True)
    classification = models.ForeignKey(Classification, on_delete=models.CASCADE, null=True)
    cover = models.ImageField(upload_to='cover/', blank=True, null=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, blank=True, null=True)
    view_count = models.IntegerField(default=0, blank=True)
    liked = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='liked_videos')  # 喜欢的用户
    create_time = models.DateTimeField(auto_now_add=True, blank=True, max_length=20)
    link = models.CharField(max_length=300, blank=True, null=True)

    objects = VideoQuerySet.as_manager()

    class Meta:
        db_table = 'VIDEOS'

    def increase_view_count(self):
        self.view_count += 1
        self.save(update_fields=['view_count'])

    def switch_like(self, user):
        if user in self.liked.all():
            self.liked.remove(user)
        else:
            self.liked.add(user)

    def count_likers(self):
        return self.liked.count()

    def user_liked(self, user):
        if user in self.liked.all():
            return 0
        else:
            return 1


@receiver(models.signals.post_delete, sender=Video)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    删除FileField文件
    """

    if instance.cover:
        if os.path.isfile(instance.cover.path):
            os.remove(instance.cover.path)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm, PasswordResetForm
from django.core.exceptions import ValidationError

from .models import User


def avatar_file_size(value):
    limit = 2 * 1024 * 1024
    if value.size > limit:
        raise ValidationError('头像文件太大了，请限制在2M之内')


class SignUpForm(UserCreationForm):
    username = forms.CharField(min_length=2, max_length=30,
                               error_messages={'min_length': '用户名至少2个字', 'max_length': '用户名不能多于30个字',
                                               'required': '用户名不能为空', },
                               widget=forms.TextInput(attrs={'placeholder': '请输入用户名（2～30个字）'}))
    password1 = forms.CharField(min_length=8, max_length=16,
                                error_messages={'min_length': '密码至少8位', 'max_length': '密码不能多于16位',
                                                'required': '密码不能为空', },
                                widget=forms.PasswordInput(attrs={'placeholder': '请输入密码（8～16位）'}))
    password2 = forms.CharField(min_length=8, max_length=16,
                                error_messages={'min_length': '密码至少8位', 'max_length': '密码不能多于16位',
                                                'required': '密码不能为空（8～16位）', },
                                widget=forms.PasswordInput(attrs={'placeholder': '请确认密码（8～16位）'}))

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2',)

    error_messages = {'password_mismatch': '两次密码不一致', }


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(min_length=2, max_length=30,
                               error_messages={'min_length': '用户名至少2个字', 'max_length': '用户名不能多于30个字',
                                               'required': '用户名不能为空', },
                               widget=forms.TextInput(attrs={'placeholder': '请输入用户名（2～30个字）'}))
    password = forms.CharField(min_length=8, max_length=16,
                               error_messages={'min_length': '密码至少8位', 'max_length': '密码不能多于16个字符',
                                               'required': '密码不能为空', },
                               widget=forms.PasswordInput(attrs={'placeholder': '请输入密码（8～16位）'}))

    class Meta:
        model = User
        fields = ['username', 'password']

    error_messages = {'invalid_login': '用户名或密码错误', }


class ChangePwdForm(PasswordChangeForm):
    old_password = forms.CharField(error_messages={'required': '现在的密码不能为空', },
                                   widget=forms.PasswordInput(attrs={'placeholder': '请输入现在的密码（8～16位）'}))
    new_password1 = forms.CharField(error_messages={'required': '请输入新密码', },
                                    widget=forms.PasswordInput(attrs={'placeholder': '请输入新密码（8～16位）'}))
    new_password2 = forms.CharField(error_messages={'required': '请确认新密码', },
                                    widget=forms.PasswordInput(attrs={'placeholder': '请输入确认密码（8～16位）'}))


class ResetPwdForm(PasswordResetForm):
    username = forms.CharField(min_length=2, max_length=30, required=False,
                               error_messages={'min_length': '用户名至少2个字', 'max_length': '用户名不能多于30个字', },
                               widget=forms.TextInput(attrs={'placeholder': '请输入用户名（2～30个字）'}))
    email = forms.EmailField(required=False, error_messages={'invalid': '请输入有效的邮箱地址', },
                             widget=forms.EmailInput(attrs={'placeholder': '请输入邮箱地址'}))


class ProfileForm(forms.ModelForm):
    username = forms.CharField(min_length=2, max_length=30, required=False,
                               error_messages={'min_length': '用户名至少2个字', 'max_length': '用户名不能多于30个字', },
                               widget=forms.TextInput(attrs={'placeholder': '请输入用户名（2～30个字）'}))
    avatar = forms.ImageField(required=False, validators=[avatar_file_size],
                              widget=forms.FileInput(attrs={'class': 'n'}))

    email = forms.EmailField(required=False, error_messages={'invalid': '请输入有效的邮箱地址', },
                             widget=forms.EmailInput(attrs={'placeholder': '请输入邮箱地址'}))

    class Meta:
        model = User
        fields = ['username', 'avatar', 'email']

users/views.py
import random
import string
from datetime import datetime

from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import redirect, render, reverse, get_object_or_404
from django.views import generic

from helpers import AuthorRequiredMixin, get_page_list
from youtube.settings import ALLOWED_HOSTS, EMAIL_HOST_USER
from .forms import ProfileForm, SignUpForm, UserLoginForm, ChangePwdForm, ResetPwdForm

User = get_user_model()


def login(request):
    if 'POST' == request.method:
        next_url = request.POST.get('next', '/')
        form = UserLoginForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                # return redirect('home')
                return redirect(next_url)
        else:
            print(form.errors)
    else:
        next_url = request.GET.get('next', '/')
        form = UserLoginForm()
    print(next_url)
    return render(request, 'users/login.html', {'form': form, 'next': next_url})


def signup(request):
    if 'POST' == request.method:
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password1 = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password1)
            auth_login(request, user)
            return redirect('home')
        else:
            print(form.errors)
    else:
        form = SignUpForm()
    return render(request, 'users/signup.html', {'form': form})


def logout(request):
    auth_logout(request)
    return redirect('home')


def change_password(request):
    if 'POST' == request.method:
        form = ChangePwdForm(request.user, request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            if not user.is_staff and not user.is_superuser:
                user.save()
                update_session_auth_hash(request, user)  # 更新session 非常重要！
                messages.success(request, '修改成功')
                return redirect('users:change_password')
            else:
                messages.warning(request, '无权修改管理员密码')
                return redirect('users:change_password')
        else:
            print(form.errors)
    else:
        form = ChangePwdForm(request.user)
    return render(request, 'users/change_password.html', {'form': form})


class ProfileView(LoginRequiredMixin, AuthorRequiredMixin, generic.UpdateView):
    model = User
    form_class = ProfileForm
    template_name = 'users/profile.html'

    def get_success_url(self):
        messages.success(self.request, '保存成功')
        return reverse('users:profile', kwargs={'pk': self.request.user.pk})


class LikeListView(generic.ListView):
    model = User
    template_name = 'users/like_videos.html'
    context_object_name = 'video_list'
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(LikeListView, self).get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        page_list = get_page_list(paginator, page)
        context['page_list'] = page_list
        return context

    def get_queryset(self):
        user = get_object_or_404(User, pk=self.kwargs.get('pk'))
        videos = user.liked_videos.all().order_by('pk')
        return videos


def reset_password(request):
    if 'POST' == request.method:
        form = ResetPwdForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            try:
                user = User.objects.get(username=username, email=email)
                if user is not None:
                    token = str(hash(datetime.now()))
                    user.first_name = token[:10]
                    user.last_name = token[10:]
                    user.save()
                    send_email(token, email)
                    return render(request, 'users/reset_password_email.html')
            except User.DoesNotExist:
                messages.error(request, '用户名和邮箱地址不匹配')
        else:
            print(form.errors)
    else:
        form = ResetPwdForm()
    return render(request, 'users/reset_password.html', {'form': form})


def reset_password_done(request):
    token = request.GET.get('token', None)
    if token is None or len(token) < 10:
        messages.error(request, '无效的请求')
        return render(request, 'users/reset_error.html')
    try:
        user = User.objects.get(first_name=token[:10], last_name=token[10:])
        if user is not None:
            random_password = random_string()
            user.set_password(random_password)
            user.save()
            messages.info(request, '新密码：{}'.format(random_password))
            return render(request, 'users/reset_password_done.html')
    except User.DoesNotExist:
        messages.error(request, '无效的请求')
        return render(request, 'users/reset_error.html')


def random_string():
    letters = string.ascii_letters
    return ''.join(random.choice(letters) for _ in range(8))


def send_email(token, email):
    host = '127.0.0.1:8000'
    if len(ALLOWED_HOSTS) > 0:
        host = ALLOWED_HOSTS[0]
    html_link = 'http://{0}/users/reset_password_done/?token={1}'.format(host, token)
    subject = 'Ace-Film用户密码重设'
    message = '如果这不是您本人的操作，请忽略此邮件'
    html_message = '<p><a href="{}">点我</a>进行密码重设。为了您的账户安全，请勿向把链接发给他人！</p>'.format(html_link)
    send_mail(subject, message, EMAIL_HOST_USER, [email], html_message=html_message)

templates/users/change_password.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}


<div class="v-settings">
    <div class="ui two column grid ">
        <div class="four wide column">
            {% include "base/left_nav.html" %}
        </div>
        <div class="twelve wide column">
            <div class="v-settings-content">
                <form novalidate class="ui form" method="post">
                  {% csrf_token %}
                    <div class="sixteen wide inline field v-form-field">
                        <label>旧密码</label>
                        {{ form.old_password}}
                    </div>
                    <div class="sixteen wide inline field v-form-field">
                        <label>新密码</label>
                        {{ form.new_password1}}
                    </div>
                    <div class="sixteen wide inline field v-form-field">
                        <label>确认密码</label>
                        {{ form.new_password2}}
                    </div>
                  <button class="ui primary button" type="submit">保存</button>

                    {% include "base/form_errors.html" %}
                    {% include "base/form_messages.html" %}

                </form>
            </div>
        </div>

    </div>
</div>

{% endblock content %}

{% block javascript %}
<script type="text/javascript">
$('.ui .dropdown').dropdown();
</script>
<script src="{% static 'js/left_nav.js' %}"></script>
{% endblock javascript %}

templates/users/like_videos.html
{% extends 'base/base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}

<h3 class="ui header">我的喜欢</h3>
<div class="ui unstackable items">

    {% for item in video_list %}
    <div class="item">
        <div class="ui tiny image">
            {% thumbnail item.cover "300x200" crop="center" as im %}
            <a href="{% url 'videos:detail' item.pk %}"><img class="ui image" src="{{ im.url }}"></a>
            {% empty %}
            {% endthumbnail %}
        </div>
        <div class="middle aligned content">
            <a class="header" href="{% url 'videos:detail' item.pk %}">{{ item.title }}</a>
        </div>
    </div>
    {% empty %}
    <h3>暂无数据</h3>
    {% endfor %}

</div>


{% include "base/page_nav.html" %}

{% endblock content %}

templates/users/login.html
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0" name="viewport">
    <link href="{% static 'img/favicon.ico' %}" rel="icon" type="image/x-icon">
    <title>登录</title>
    <link href="https://cdn.staticfile.org/semantic-ui/2.4.1/semantic.min.css" rel="stylesheet" type="text/css">
    <link href="{% static 'css/semantic.custom.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
</head>
<body id="v-account-body">
<div class="ui middle aligned center aligned grid">
    <div class="column v-account">
        <h2 class="ui teal image header">
            <img class="image" src="{% static 'img/logo.png' %}">
            <div class="content">登录账户</div>
        </h2>
        <form action="{% url 'users:login' %}" class="ui large form" enctype="multipart/form-data" method="post"
              novalidate>
            {% csrf_token %}
            <div class="ui stacked segment">
                <div class="field">
                    <div class="ui left icon input">
                        <i class="user icon"></i>
                        {{form.username}}
                    </div>
                </div>
                <div class="field">
                    <div class="ui left icon input">
                        <i class="lock icon"></i>
                        {{form.password}}
                    </div>
                </div>
                <input name="next" type="hidden" value="{{ next }}"/>
                <button class="ui fluid large teal submit button" type="submit">登录</button>
            </div>

            {% include "base/form_errors.html" %}

        </form>
            <span class="float-left"><a href="{% url 'users:signup' %}">注册账号</a></span>
            <span class="float-right"><a href="{% url 'users:reset_password' %}">忘记密码</a></span>
    </div>
</div>
</body>
</html>

templates/users/profile.html
{% extends 'base/base.html' %}
{% load static %}
{% load thumbnail %}
{% block content %}


<div class="v-settings">
    <div class="ui two column grid ">
        <div class="four wide column">
            {% include "base/left_nav.html" %}
        </div>
        <div class="twelve wide column">
            <div class="v-settings-content">

                <form action="{% url 'users:profile' form.instance.pk %}" class="ui form" enctype="multipart/form-data" method="post"
                      novalidate role="form">
                    {% csrf_token %}
                    <div class="sixteen wide inline field v-form-field">
                        <label>头像</label>
                        <div class="v-inline-middle">
                            <label for="id_avatar">
                                {% thumbnail user.avatar "200x200" crop="center" as im %}
                                <img class="ui mini circular image" src="{{ im.url }}">
                                {% empty %}
                                <img class="ui mini circular  image" src="{% static 'img/img_default_avatar.png' %}">
                                {% endthumbnail %}
                            </label>
                            {{form.avatar}}
                            <span class="n" id="file_is_choose">文件已选择</span>

                        </div>
                    </div>

                    <div class="sixteen wide inline field v-form-field">
                        <label>用户名</label>
                        {{form.username}}
                    </div>

                    <div class="sixteen wide inline field v-form-field">
                        <label>邮箱</label>
                        {{form.email}}
                    </div>

                    <button class="ui primary button" type="submit">保存</button>

                    {% include "base/form_errors.html" %}
                    {% include "base/form_messages.html" %}

                </form>
            </div>
        </div>

    </div>
</div>

{% endblock content %}

{% block javascript %}
<script type="text/javascript">

$(function(){

    $('.ui .dropdown').dropdown();

    $("#id_avatar").change(function(){
        $("#file_is_choose").show()
    });

});


</script>
<script src="{% static 'js/left_nav.js' %}"></script>
{% endblock javascript %}

templates/users/reset_error.html
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0" name="viewport">
    <link href="{% static 'img/favicon.ico' %}" rel="icon" type="image/x-icon">
    <title>出错了</title>
    <link href="https://cdn.staticfile.org/semantic-ui/2.4.1/semantic.min.css" rel="stylesheet" type="text/css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
</head>
<body id="v-account-body">
<div class="ui middle aligned center aligned grid">
    <div class="column v-account">
        <h2 class="ui teal image header">
            <img class="image" src="{% static 'img/logo.png' %}">
            <div class="content">出现了错误</div>
        </h2>
        <h3>
            {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                    <p class="{{ message.tags }}" >{{ message }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            <p class="sixteen wide inline field v-form-field"><a href="{% url 'users:reset_password' %}">重新发送</a></p>
        </h3>
    </div>
</div>
</body>
</html>

templates/users/reset_password.html
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0" name="viewport">
    <link href="{% static 'img/favicon.ico' %}" rel="icon" type="image/x-icon">
    <title>重设密码</title>
    <link href="https://cdn.staticfile.org/semantic-ui/2.4.1/semantic.min.css" rel="stylesheet" type="text/css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
</head>
<body id="v-account-body">
<div class="ui middle aligned center aligned grid">
    <div class="column v-account">
        <h2 class="ui teal image header">
            <img class="image" src="{% static 'img/logo.png' %}">
            <div class="content">重设密码</div>
        </h2>
        <form method="post" role="form">
            {% csrf_token %}
            <div class="ui stacked segment">
                <div class="field">
                    <div class="sixteen wide inline field v-form-field">
                        <label>用户</label>
                        {{form.username}}
                    </div>
                </div>
                <div class="sixteen wide inline field v-form-field">
                    <label class="content">邮箱</label>
                    {{form.email}}
                </div>
                <button class="ui primary button" type="submit">发送邮件</button>
                {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                    <p class="{{ message.tags }}" >{{ message }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </form>
    </div>
</div>
</body>
</html>

templates/users/reset_password_done.html
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0" name="viewport">
    <link href="{% static 'img/favicon.ico' %}" rel="icon" type="image/x-icon">
    <title>密码已重设</title>
    <link href="https://cdn.staticfile.org/semantic-ui/2.4.1/semantic.min.css" rel="stylesheet" type="text/css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
</head>
<body id="v-account-body">
<div class="ui middle aligned center aligned grid">
    <div class="column v-account">
        <h2 class="ui teal image header">
            <img class="image" src="{% static 'img/logo.png' %}">
            <div class="content">密码已重设</div>
        </h2>
        <h3>
            <p class="sixteen wide inline field v-form-field">您的密码已经被系统重置，请重新<a href="{% url 'users:login' %}">登录</a>修改密码</p>
            {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                    <p class="{{ message.tags }}" >{{ message }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </h3>
    </div>
</div>
</body>
</html>

templates/users/reset_password_email.html
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0" name="viewport">
    <link href="{% static 'img/favicon.ico' %}" rel="icon" type="image/x-icon">
    <title>邮件已发送</title>
    <link href="https://cdn.staticfile.org/semantic-ui/2.4.1/semantic.min.css" rel="stylesheet" type="text/css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
</head>
<body id="v-account-body">
<div class="ui middle aligned center aligned grid">
    <div class="column v-account">
        <h2 class="ui teal image header">
            <img class="image" src="{% static 'img/logo.png' %}">
            <div class="content">邮件已发送</div>
        </h2>
        <h3>我们已经向您发送了包含重设密码链接的邮件～</h3>
    </div>
</div>
</body>
</html>

templates/users/signup.html
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <meta content="IE=edge, chrome=1" http-equiv="X-UA-Compatible"/>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0" name="viewport">
    <link href="{% static 'img/favicon.ico' %}" rel="icon" type="image/x-icon">
    <title>注册</title>
    <link href="https://cdn.staticfile.org/semantic-ui/2.4.1/semantic.min.css" rel="stylesheet" type="text/css">
    <link href="{% static 'css/semantic.custom.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
</head>
<body id="v-account-body">
<div class="ui middle aligned center aligned grid">
    <div class="column v-account">
        <h2 class="ui teal image header">
            <img class="image" src="{% static 'img/logo.png' %}">
            <div class="content">注册账户</div>
        </h2>
        <form action="{% url 'users:signup' %}" class="ui large form" enctype="multipart/form-data" method="post"
              novalidate>
            {% csrf_token %}
            <div class="ui stacked segment">
                <div class="field">
                    <div class="ui left icon input">
                        <i class="user icon"></i>
                        {{form.username}}
                    </div>
                </div>
                <div class="field">
                    <div class="ui left icon input">
                        <i class="lock icon"></i>
                        {{form.password1}}
                    </div>
                </div>
                <div class="field">
                    <div class="ui left icon input">
                        <i class="lock icon"></i>
                        {{form.password2}}
                    </div>
                </div>
                <button class="ui fluid large teal submit button" type="submit">注册</button>
                <p class="sixteen wide inline field v-form-field">^_^注册后在个人资料中及时留下邮箱不定期收获最新福利^_^</p>
            </div>
            {% include "base/form_errors.html" %}
        </form>

        <div class="ui message">已有账号？<a href="{% url 'users:login' %}">登录</a></div>
    </div>
</div>
</body>
</html>